steps:
- name: 'busybox'
  args: ['sleep', '10']
gitConfig:
  http:
    proxySecretVersionName: 'projects/96774389270/secrets/giangnguyen-secret/versions/latest'
source:
  gitSource:
    url: 'https://github.com/GiangN/gcp-test'
    revision: 'main'
